{{
    config(
        materialized='incremental',
        unique_key='POSITION_EVENT_PK'
        )
}}

WITH
POSITION_EVENTS AS (
    SELECT *, 'WKD' AS REC_SRC, 
    IFF(POSITION_ID_CREATED IS NULL, regexp_substr(POSITION_ID,'P_[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'), POSITION_ID_CREATED ) AS POSITION_ID_DERIVED
    FROM {{ source('STAGING','STG_WKD_POSITION_EVENTS') }} 
),

POSITION AS (
    SELECT POSITION_ID AS POSITIONID, POSITION_SK, EFF_DT, DISC_DT FROM {{ ref('DIM_POSITION') }}
),

JOB_DESC AS (
    SELECT POSITION_ID AS POSITIONID_JOB_DESC, JOB_DESC_SK, EFF_DT, DISC_DT FROM {{ ref('DIM_JOB_DESC') }}
)

SELECT 
POSITION_EVENT_PK,
POSITION_SK,
JOB_DESC_SK,
POSITION_ID_DERIVED AS POSITION_ID,
POSITION,
POSITION_ID_CREATED,
POSITION_BP_WID,
WORKER_BP_WID,
BP_EVENT_COMPLETED_WID,
BP_STEP_COMPLETED_BY_EMP_ID,
POSITION_OR_HIRING_RESTRICTIONS,
JOB_DESC_CURR,
JOB_DESC_PROPOSED,
BP_TRANSACTION,
BP_TYPE,
BP_REASON,
EVENT_RECORD,
TRANSACTION_STATUS,
EFF_DT,
BP_EVENT_COMPLETED_DTM,
BP_EVENT_COMPLETED_DT,
REC_SRC,
INS_BATCH_ID
FROM  (
SELECT 
    {{ dbt_utils.surrogate_key(['BP_EVENT_COMPLETED_WID'])}} AS POSITION_EVENT_PK,
    COALESCE(POSITION.POSITION_SK, '-1') AS POSITION_SK,
    COALESCE(JOB_DESC.JOB_DESC_SK, '-1') AS JOB_DESC_SK,
    POSITION_ID_DERIVED,
    POSITION_ID AS POSITION,
    POSITION_ID_CREATED AS POSITION_ID_CREATED,
    POSITION_BP_WID AS POSITION_BP_WID,
    WORKER_BP_WID AS WORKER_BP_WID,
    BP_EVENT_COMPLETED_WID AS BP_EVENT_COMPLETED_WID,
    BP_STEP_COMPLETED_BY_EIN AS BP_STEP_COMPLETED_BY_EMP_ID,
    POSITION_OR_HIRING_RESTRICTIONS AS POSITION_OR_HIRING_RESTRICTIONS,
    JOB_DESCRIPTION_CURRENT AS JOB_DESC_CURR,
    JOB_DESCRIPTION_PROPOSED AS JOB_DESC_PROPOSED,
    BP_TRANSACTION AS BP_TRANSACTION,
    BUSINESS_PROCESS_TYPE AS BP_TYPE,
    BUSINESS_PROCESS_REASON_TEXT AS BP_REASON,
    EVENT_RECORD AS EVENT_RECORD,
    TRANSACTION_STATUS AS TRANSACTION_STATUS,
    EFFECTIVE_DT AS EFF_DT,
    BP_EVENT_COMPLETED_DTM AS BP_EVENT_COMPLETED_DTM,
    BP_EVENT_COMPLETED_DT AS BP_EVENT_COMPLETED_DT,
    REC_SRC AS REC_SRC,
    TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) as INS_BATCH_ID,
    ROW_NUMBER() OVER(PARTITION BY BP_EVENT_COMPLETED_WID ORDER BY BP_EVENT_COMPLETED_DT DESC) RN

FROM POSITION_EVENTS

LEFT JOIN POSITION
ON POSITION_EVENTS.POSITION_ID_DERIVED = POSITION.POSITIONID 
AND TO_DATE(POSITION_EVENTS.BP_EVENT_COMPLETED_DT) BETWEEN TO_DATE(POSITION.EFF_DT) AND TO_DATE(POSITION.DISC_DT)

LEFT JOIN JOB_DESC
ON POSITION_EVENTS.POSITION_ID_DERIVED = JOB_DESC.POSITIONID_JOB_DESC
AND TO_DATE(POSITION_EVENTS.BP_EVENT_COMPLETED_DT) BETWEEN TO_DATE(JOB_DESC.EFF_DT) AND TO_DATE(JOB_DESC.DISC_DT)


{% if is_incremental() %}
    WHERE (POSITION_EVENTS.BP_EVENT_COMPLETED_DT >= '{{ get_max_event_time('BP_EVENT_COMPLETED_DT') }}'
        OR 
    POSITION_EVENT_PK IN (
        SELECT POSITION_EVENT_PK FROM {{ this }}
        WHERE POSITION_SK = '-1' OR JOB_DESC_SK = '-1' )
    )
{% endif %}

)WHERE RN=1
