{{
    config(
        materialized='incremental',
        unique_key='NOTIFICATION_PK'
        )
}}

WITH
STG_WKD_REFERRALS_EVENT AS (
    SELECT *, 'WKD' as REC_SOURCE, 1 AS BATCH_KEY_ID FROM {{ source('STAGING','STG_WKD_NOTIFICATION_EVENTS') }}
)

SELECT
    {{ dbt_utils.surrogate_key(['NOTIFICATION_WID'])}} AS NOTIFICATION_PK,
    NOTIFICATION_WID AS NOTIFICATION_WID,
    INITIATOR_EIN AS INITIATOR_EMP_ID,
    WORKER_ON_BP_EIN AS WORKER_ON_BP_EMP_ID,
    NOTIFICATION_GENERATION_DT AS GENERATION_DT,
    PART_OF_ANOTHER_BP_OF_TYPE AS DOMAIN,
    BP_TYPE AS BP_TYPE,
    BP AS BP,
    BP_EVENT AS BP_EVENT,
    CHANNELS AS CHANNELS,
    NOTIFICATION_SUBJECT AS SUBJECT,
    MESSAGE AS MESSAGE,
    RECIPIENTS AS RECIPIENTS,
    TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) AS INS_BATCH_ID,
    TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) AS UPD_BATCH_ID
FROM STG_WKD_REFERRALS_EVENT STG
{% if is_incremental() %}
    WHERE STG.NOTIFICATION_GENERATION_DT >= '{{ get_max_event_time('GENERATION_DT') }}'
{% endif %}
QUALIFY ROW_NUMBER() OVER(PARTITION BY NOTIFICATION_WID ORDER BY NOTIFICATION_GENERATION_DT DESC ) = 1

