{{
    config(
        materialized='incremental',
        unique_key='REFERRAL_PK',
        full_refresh=false
        )
}}

WITH
STG_WKD_REFERRALS_EVENT AS (
    SELECT *
    , 'WKD' as REC_SOURCE
    FROM {{ source('STAGING','STG_WKD_REFERRALS_EVENT') }}
    QUALIFY ROW_NUMBER() OVER(PARTITION BY REFERRAL_BP_WID ORDER BY BP_EVENT_COMPLETED_DT DESC ) = 1
),

EMPLOYEE AS (
    SELECT EMP_SK, EMP_ID, EFF_DT, DISC_DT FROM {{ ref('DIM_EMPLOYEE') }}
)

SELECT
REFERRAL_PK,
EMP_SK,
REFERRAL_BP_WID,
BP_EVENT_COMPLETED_WID,
REFERRER_EMP_ID,
BP_TRANSACTION,
BP_EVENT_COMPLETED_DTM,
BP_EVENT_COMPLETED_DT,
REC_SRC,
INS_BATCH_ID,
UPD_BATCH_ID
FROM
(
SELECT
    {{ dbt_utils.surrogate_key(['REFERRAL_BP_WID'])}} AS REFERRAL_PK,
    COALESCE(EMP.EMP_SK, '-1') AS EMP_SK,
    STG.Referral_BP_WID as REFERRAL_BP_WID,
    STG.BP_Event_Completed_WID as BP_EVENT_COMPLETED_WID,
    STG.BP_Step_Completed_By_EIN as REFERRER_EMP_ID,
    STG.BP_Transaction as BP_TRANSACTION,
    STG.BP_Event_Completed_DTM as BP_EVENT_COMPLETED_DTM,
    STG.BP_Event_Completed_DT as BP_EVENT_COMPLETED_DT,
    STG.REC_SOURCE as REC_SRC,
    TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) AS INS_BATCH_ID,
    TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) AS UPD_BATCH_ID
FROM STG_WKD_REFERRALS_EVENT STG
LEFT JOIN EMPLOYEE EMP ON EMP.EMP_ID = STG.BP_STEP_COMPLETED_BY_EIN
    AND STG.BP_EVENT_COMPLETED_DT BETWEEN EMP.EFF_DT AND EMP.DISC_DT
{% if is_incremental() %}
    WHERE (STG.BP_EVENT_COMPLETED_DT >= '{{ get_max_event_time('BP_EVENT_COMPLETED_DT') }}'
        OR 
    REFERRAL_PK IN (
        SELECT REFERRAL_PK FROM {{ this }}
        WHERE EMP_SK='-1' )
    )
{% endif %}
)
