{{
    config(
        materialized='incremental',
        unique_key='CALIB_EVENT_PK'
        )
}}

WITH
CALIB_REVIEW AS (
    SELECT *, 'WKD' AS REC_SRC
    FROM {{ source('STAGING','STG_WKD_WORKER_TALENT_CALIBRATION_EVENTS') }} 
),

EMPLOYEE AS (
    SELECT EMP_ID AS EMPID, EMP_SK, EFF_DT, DISC_DT FROM {{ ref('DIM_EMPLOYEE') }}
)

SELECT 
CALIB_EVENT_PK,
EMP_SK,
EMP_ID,
WORKER_WID,
CALIB_WID,
CALIB_ACTION_EVENT,
CREATED_BY,
DENIED_BY_WORKER,
APPROVED_BY_WORKERS,
TRANSACTION_STATUS,
CALIB_BOX_COMPLETED_VALUE_SENS,
CALIB_BOX_VALUE_NBR_SENS,
CALIB_VALUE_COLUMN_SENS,
CALIB_VALUE_ROW_SENS,
INITIATED_DTM,
COMPLETED_DTM,
COMPLETED_DT,
EFF_DT,
REC_SRC,
INS_BATCH_ID

FROM(
    SELECT 
    {{ dbt_utils.surrogate_key(['CALIBRATION_WID'])}} AS CALIB_EVENT_PK, 
    COALESCE(EMPLOYEE.EMP_SK, '-1') AS EMP_SK,
    EIN AS EMP_ID,
    WORKER_WID AS WORKER_WID,
    CALIBRATION_WID AS CALIB_WID,
    CALIBRATION_ACTION_EVENT AS CALIB_ACTION_EVENT,
    CALIBRATION_CREATED_BY AS CREATED_BY,
    CALIBRATION_DENIED_BY_WORKER AS DENIED_BY_WORKER,
    CALIBRATION_APPROVED_BY_WORKERS AS APPROVED_BY_WORKERS,
    CALIBRATION_TRANSACTION_STATUS AS TRANSACTION_STATUS,
    CALIBRATION_BOX_COMPLETED_VALUE_SENS AS CALIB_BOX_COMPLETED_VALUE_SENS,
    CALIBRATION_BOX_VALUE_NUM_SENS AS CALIB_BOX_VALUE_NBR_SENS,
    CALIBRATION_VALUE_COLUMN_SENS AS CALIB_VALUE_COLUMN_SENS,
    CALIBRATION_VALUE_ROW_SENS AS CALIB_VALUE_ROW_SENS,
    CALIBRATION_INITIATED_DTM AS INITIATED_DTM,
    CALIBRATION_COMPLETED_DTM AS COMPLETED_DTM,
    CALIBRATION_COMPLETED_DT AS COMPLETED_DT,
    CALIBRATION_EFFECTIVE_DT AS EFF_DT,
    REC_SRC AS REC_SRC,
    TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) as INS_BATCH_ID,
    ROW_NUMBER() OVER(PARTITION BY CALIBRATION_WID ORDER BY CALIBRATION_COMPLETED_DT DESC) RN

FROM CALIB_REVIEW

LEFT JOIN EMPLOYEE
ON CALIB_REVIEW.EIN = EMPLOYEE.EMPID
AND TO_DATE(CALIB_REVIEW.CALIBRATION_COMPLETED_DT) BETWEEN TO_DATE(EMPLOYEE.EFF_DT) AND TO_DATE(EMPLOYEE.DISC_DT)

{% if is_incremental() %}
    WHERE (CALIB_REVIEW.CALIBRATION_COMPLETED_DT >= '{{ get_max_event_time('COMPLETED_DT') }}'
        OR 
    CALIB_EVENT_PK IN (
        SELECT CALIB_EVENT_PK FROM {{ this }}
        WHERE EMP_SK = '-1' )
    )
{% endif %}

)WHERE RN=1