{{
    config(
        materialized='incremental',
        unique_key='TIME_OFF_EVENT_PK',
        tags=["core","fact","scheduled-daily"],
        full_refresh=false
        )
}}

WITH
STG_WKD_ALL_TIMEOFF_EVENT AS (
    SELECT stg.*, 'WKD' AS REC_SRC, 1 AS BATCH_KEY_ID
    from {{ source('STAGING','STG_WKD_ALL_TIMEOFF_EVENT') }} stg
    qualify row_number() over(partition by time_off_bp_action_wid, bp_event_step_completed_wid order by BP_EVENT_COMPLETED_DT desc) = 1
),

DIM_TIME_OFF AS (
    SELECT TIME_OFF_BP_ACTION_WID, TIME_OFF_SK FROM {{ ref('DIM_TIME_OFF') }}
),

DIM_EMPLOYEE AS (
    SELECT EMP_ID, EFF_DT, DISC_DT, EMP_SK FROM {{ ref('DIM_EMPLOYEE') }}
)

SELECT
    {{ dbt_utils.surrogate_key(['STG.TIME_OFF_BP_ACTION_WID', 'STG.BP_EVENT_STEP_COMPLETED_WID'])}} as TIME_OFF_EVENT_PK,
    COALESCE(TIMEOFF.TIME_OFF_SK,'-1') AS TIME_OFF_SK,
    COALESCE(EMP.EMP_SK,'-1') AS EMP_SK,
    STG.EMPLOYEE_ID AS EMP_ID,
    STG.TIME_OFF_BP_ACTION_WID AS TIME_OFF_BP_ACTION_WID,
    STG.BP_EVENT_STEP_COMPLETED_WID AS BP_EVENT_STEP_COMPLETED_WID,
    STG.TIME_OFF_BP_ACTION AS TIME_OFF_BP_ACTION,
    STG.TIME_OFF_BP_TYPE AS TIME_OFF_BP_TYPE,
    STG.BP_DEFINITION AS BP_DEF,
    STG.BP_TRANSACTION_STATUS AS BP_TRANSACTION_STATUS,
    STG.BP_EFFECTIVE_DT AS BP_EFF_DT,
    STG.BP_REASON_SENS AS BP_REASON_SENS,
    STG.BP_CORRECTIONS AS BP_CORRECTIONS,
    STG.BP_LAST_UPD_BY AS BP_LAST_UPD_BY,
    STG.BP_EVENT_INITIATED_DTM AS BP_EVENT_INITIATED_DTM,
    STG.BP_EVENT_INITIATED_DT AS BP_EVENT_INITIATED_DT,
    STG.BP_EVENT_COMPLETED_DTM AS BP_EVENT_COMPLETED_DTM,
    STG.BP_EVENT_COMPLETED_DT AS BP_EVENT_COMPLETED_DT,
    STG.BP_STEP_TYPE AS BP_STEP_TYPE,
    STG.BP_STEP_ORDER AS BP_STEP_ORDER,
    STG.BP_EVENT_RECORD AS BP_EVENT_REC,
    STG.BP_STEP_DESCRIPTION AS BP_STEP_DESC,
    STG.BP_STEP_STATUS AS BP_STEP_STATUS,
    STG.BP_STEP_INITIATED_DTM AS BP_STEP_INITIATED_DTM,
    STG.BP_STEP_COMPLETED_DTM AS BP_STEP_COMPLETED_DTM,
    STG.BP_STEP_COMPLETED_BY_NAME AS BP_STEP_COMPLETED_BY_NAME,
    STG.BP_STEP_COMPLETED_BY_EIN AS BP_STEP_COMPLETED_BY_EIN,
    TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) as INS_BATCH_ID,
    STG.REC_SRC AS REC_SRC
FROM STG_WKD_ALL_TIMEOFF_EVENT STG
LEFT JOIN DIM_TIME_OFF TIMEOFF ON TIMEOFF.TIME_OFF_BP_ACTION_WID = STG.TIME_OFF_BP_ACTION_WID
LEFT JOIN DIM_EMPLOYEE EMP ON EMP.EMP_ID = STG.EMPLOYEE_ID
    and STG.BP_EFFECTIVE_DT between to_date(emp.eff_dt) and to_date(emp.disc_dt)
{% if is_incremental() %}
    WHERE (STG.BP_EVENT_COMPLETED_DT >= '{{ get_max_event_time('BP_EVENT_COMPLETED_DT') }}'
    OR
    TIME_OFF_EVENT_PK IN (
        SELECT TIME_OFF_EVENT_PK FROM {{ this }}
        WHERE TIME_OFF_SK='-1' OR EMP_SK='-1' )
    )
{% endif %}
