{{
    config(
        materialized='incremental',
        unique_key='TALENT_REVIEW_PK'
        )
}}

WITH
TALENT_REVIEW AS (
    SELECT *, 'WKD' AS REC_SRC
    FROM {{ source('STAGING','STG_WKD_WORKER_TALENT_REVIEW_EVENTS') }} 
),

EMPLOYEE AS (
    SELECT EMP_ID AS EMPID, EMP_SK, EFF_DT, DISC_DT FROM {{ ref('DIM_EMPLOYEE') }}
)

SELECT 
TALENT_REVIEW_PK,
EMP_SK,
EMP_ID,
WORKER_WID,
EVENT_WID,
ACTION_EVENT,
INITIATED_DTM,
COMPLETED_DTM,
COMPLETED_DT,
TRANSACTION_STATUS,
MATRIX_REVIEW_RATING_SENS,
POTENTIAL_SENS,
RETENTION_RISK_SENS,
ACHIEVABLE_LEVEL_SENS,
LOSS_IMPACT_SENS,
REC_SRC,
INS_BATCH_ID
FROM(
    SELECT 
    {{ dbt_utils.surrogate_key(['TALENT_REVIEW_EVENTS_WID'])}} AS TALENT_REVIEW_PK, 
    COALESCE(EMPLOYEE.EMP_SK, '-1') AS EMP_SK,
    EIN AS EMP_ID,
    WORKER_WID AS WORKER_WID,
    TALENT_REVIEW_EVENTS_WID AS EVENT_WID,
    TALENT_REVIEW_ACTION_EVENT AS ACTION_EVENT,
    TALENT_REVIEW_INITIATED_DTM AS INITIATED_DTM,
    TALENT_REVIEW_COMPLETED_DTM AS COMPLETED_DTM,
    TALENT_REVIEW_COMPLETED_DT AS COMPLETED_DT,
    TALENT_REVIEW_TRANSACTION_STATUS AS TRANSACTION_STATUS,
    TALENT_REVIEW_TALENT_MATRIX_REVIEW_RATING_SENS AS MATRIX_REVIEW_RATING_SENS,
    TALENT_REVIEW_POTENTIAL_SENS AS POTENTIAL_SENS,
    TALENT_REVIEW_RETENTION_RISK_SENS AS RETENTION_RISK_SENS,
    TALENT_REVIEW_ACHIEVABLE_LEVEL_SENS AS ACHIEVABLE_LEVEL_SENS,
    TALENT_REVIEW_LOSS_IMPACT_SENS AS LOSS_IMPACT_SENS,
    REC_SRC AS REC_SRC,
    TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) as INS_BATCH_ID,
    ROW_NUMBER() OVER(PARTITION BY TALENT_REVIEW_EVENTS_WID ORDER BY TALENT_REVIEW_COMPLETED_DT DESC) RN


FROM TALENT_REVIEW

LEFT JOIN EMPLOYEE
ON TALENT_REVIEW.EIN = EMPLOYEE.EMPID
AND TO_DATE(TALENT_REVIEW.TALENT_REVIEW_COMPLETED_DT) BETWEEN TO_DATE(EMPLOYEE.EFF_DT) AND TO_DATE(EMPLOYEE.DISC_DT)

{% if is_incremental() %}
    WHERE (TALENT_REVIEW.TALENT_REVIEW_COMPLETED_DT >= '{{ get_max_event_time('COMPLETED_DT') }}'
        OR 
    TALENT_REVIEW_PK IN (
        SELECT TALENT_REVIEW_PK FROM {{ this }}
        WHERE EMP_SK = '-1' )
    )
{% endif %}

)WHERE RN=1