{{
    config(
        materialized='incremental',
        unique_key='QSTR_PK'
        )
}}

WITH
STG_QUESTIONNAIRE AS (
    SELECT *, 'WKD' AS REC_SRC, TRIM(SUBSTRING(REQUISITION_ID,1,CHARINDEX(' ',TRIM(REQUISITION_ID) ) )) AS REQID, 1 AS BATCH_KEY_ID 
    FROM {{ source('STAGING','STG_WKD_QUESTIONNAIRE') }} 
),

REQUISITION AS (
    SELECT JOB_REQ_ID AS REQ_ID, JOB_REQ_SK FROM {{ ref('DIM_REQUISITION') }}
),

POSITION AS (
    SELECT POSITION_ID AS POSITIONID, POSITION_SK, EFF_DT, DISC_DT FROM {{ ref('DIM_POSITION') }}
),

EMPLOYEE AS (
    SELECT EMP_ID AS EMPID, EMP_SK, EFF_DT, DISC_DT FROM {{ ref('DIM_EMPLOYEE') }}
)

SELECT 
QSTR_PK,
JOB_REQ_SK,
POSITION_SK,
EMP_SK,
QSTR_ANSWER_WID,
QSTR_RESPONSE_WID,
QR_CONTEXT,
EMP_ID,
POSITION_ID,
JOB_REQ_ID,
COST_CENTER,
RESPONDENT_EMP_ID,
RESPONDENT,
SUBMISSION_DT,
SUBMISSION_DT_SK,
BP_TRANSACTION,
QSTR_TYPE,
QST_ITEM,
QST_BODY,
QSTR_ANSWER,
SCORE_NUM,
ROW_SEQ,
REC_SRC,
INS_BATCH_ID
FROM (

SELECT 
    {{ dbt_utils.surrogate_key(['QUESTIONNAIRE_ANSWER_WID'])}} AS QSTR_PK,
    COALESCE(REQUISITION.JOB_REQ_SK, '-1') AS JOB_REQ_SK,
    COALESCE(POSITION.POSITION_SK, '-1') AS POSITION_SK, 
    COALESCE(EMPLOYEE.EMP_SK, '-1') AS EMP_SK, 
    QUESTIONNAIRE_ANSWER_WID AS QSTR_ANSWER_WID,
    QUESTIONNAIRE_RESPONSE_WID AS QSTR_RESPONSE_WID,
    QR_CONTEXT AS QR_CONTEXT,
    EIN AS EMP_ID,
    POSITION_ID AS POSITION_ID,
    REQUISITION_ID AS JOB_REQ_ID,
    COST_CENTER AS COST_CENTER,
    RESPONDENT_EIN AS RESPONDENT_EMP_ID,
    RESPONDENT AS RESPONDENT,
    SUBMISSION_DT AS SUBMISSION_DT,
    TO_NUMBER(TO_VARCHAR(SUBMISSION_DT::DATE, 'YYYYMMDD')) AS SUBMISSION_DT_SK,
    BP_TRANSACTION AS BP_TRANSACTION,
    QUESTIONNAIRE_TYPE AS QSTR_TYPE,
    QUESTION_ITEM AS QST_ITEM,
    QUESTION_BODY AS QST_BODY,
    QUESTIONNAIRE_ANSWER AS QSTR_ANSWER,
    SCORE_NUM AS SCORE_NUM,
    ROW_SEQ AS ROW_SEQ,
    REC_SRC AS REC_SRC,
    TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) as INS_BATCH_ID, 
    ROW_NUMBER() OVER(PARTITION BY QUESTIONNAIRE_ANSWER_WID ORDER BY SUBMISSION_DT DESC) RN

FROM STG_QUESTIONNAIRE


LEFT JOIN REQUISITION
ON STG_QUESTIONNAIRE.REQID = REQUISITION.REQ_ID
--AND TO_DATE(STG.SUBMISSION_DT) BETWEEN TO_DATE(REQ.EFF_DT) AND TO_DATE(REQ.DISC_DT) --removed as DIM_REQ is Type1

LEFT JOIN POSITION
ON STG_QUESTIONNAIRE.POSITION_ID = POSITION.POSITIONID 
AND TO_DATE(STG_QUESTIONNAIRE.SUBMISSION_DT) BETWEEN TO_DATE(POSITION.EFF_DT) AND TO_DATE(POSITION.DISC_DT)

LEFT JOIN EMPLOYEE
ON STG_QUESTIONNAIRE.EIN = EMPLOYEE.EMPID
AND TO_DATE(STG_QUESTIONNAIRE.SUBMISSION_DT) BETWEEN TO_DATE(EMPLOYEE.EFF_DT) AND TO_DATE(EMPLOYEE.DISC_DT)


{% if is_incremental() %}
    WHERE 
    
    (STG_QUESTIONNAIRE.SUBMISSION_DT >= '{{ get_max_event_time('SUBMISSION_DT') }}'
    OR 
    QSTR_PK IN (
        SELECT QSTR_PK FROM {{ this }}
        WHERE JOB_REQ_SK ='-1' OR POSITION_SK = '-1' OR EMP_SK = '-1'
        )
    )
{% endif %}

)WHERE RN=1