version: 2

sources:
      
  - name: STAGING
    tables:
      - name: STG_WKD_RECRUITING_AGENCY
      - name: STG_WKD_JOB_REQUISITION
      - name: STG_WKD_JOB_POSTING
      - name: STG_WKD_POSITION
      - name: STG_WKD_JOB_APPLICATION
      - name: STG_WKD_CANDIDATE_PROFILE
      - name: STG_WKD_JOB_APPLICATION_QUESTIONNAIRE
      - name: STG_WKD_JOB_REQUISITION_EVENT
      - name: STG_WKD_JOB_APPLICATION_EVENT
      - name: STG_WKD_EMPLOYEE_EXTRACT
      - name: STG_WKD_CANDIDATE_INTERVIEWS
      - name: STG_WKD_QUESTIONNAIRE
      - name: STG_WKD_POSITION_BKP
      - name: STG_WKD_JOB_CODE
      - name: STG_WKD_ALL_WORKER_EVENTS
      - name: STG_WKD_WORKER_POSITION_CHANGES
      - name: STG_WKD_SECURITY_USER_BASED
      - name: STG_WKD_WORKER_TALENT_REVIEW_EVENTS
      - name: STG_WKD_POSITION_INTERIM
      - name: STG_WKD_WORKER_TALENT_CALIBRATION_EVENTS
      - name: STG_WKD_POSITION_EVENTS
      - name: STG_WKD_EVENT_CLASSIFICATION
      - name: STG_WKD_UNION
      - name: STG_WKD_ROLE_ASSIGNMENTS_BY_ORG
      - name: STG_WKD_COMPENSATION_PLAN
      - name: STG_WKD_BUSINESS_PROCESS
      - name: STG_WKD_PAY_COMPONENT_GROUPS
      - name: STG_WKD_PAY_ACCUMULATORS
      - name: STG_WKD_PAYCODE_EARNINGS
      - name: STG_WKD_PAYCODE_DEDUCTIONS
      - name: STG_WKD_COMPANY
      - name: STG_DIM_ORGANIZATION
      - name: STG_WKD_COMPENSATION_GRADES_PROFILES
      - name: STG_WKD_SUPERVISOR_ORG
      - name: STG_WKD_PAYROLL_RESULT_DETAIL
      - name: STG_WKD_COMPENSATION_CHANGE_EVENTS
      - name: STG_WKD_LOCATION
      - name: STG_WKD_WORKER_TIME_OFF
      - name: STG_WKD_ALL_TIMEOFF_EVENT
      - name: STG_WKD_PAY_COMPONENT_RELATED_CALCULATIONS
      - name: STG_WKD_COSTING_ALLOCATIONS
      - name: STG_WKD_PAY_COMP_EARNING
      - name: STG_WKD_PAY_COMP_DEDUCTION
      - name: STG_WKD_REFERRALS_EVENT
      - name: STG_WKD_EMPLOYEE_EXTRACT_INITIAL_BULK_LOAD
      - name: STG_WKD_NOTIFICATION_EVENTS
      - name: STG_WORKFORCE_KRONOS
  
  - name: DEVELOP
    tables: 
      - name: DIM_EMPLOYEE_EVENTS
      - name: DIM_EMPLOYEE

  
  - name: CORE
    tables:
      - name: DIM_AGENCY
      - name: DIM_APPLICATION
      - name: DIM_CANDIDATE
      - name: DIM_EMPLOYEE
      - name: DIM_POSITION
      - name: DIM_REQUISITION
      - name: FACT_CANDIDATE_INTERVIEWS
      - name: FACT_JOB_APP_QUESTIONNAIRE
      - name: FACT_JOB_POSTING
      - name: FACT_APPLICATION_EVENT
      - name: FACT_REQUISITION_EVENT
      - name: FACT_QUESTIONNAIRE
      - name: DIM_JOB
      - name: FACT_WORKER_EVENTS
      - name: FACT_WORKER_POSITION_CHANGES
      - name: DIM_JOB_CLASS
      - name: FACT_TALENT_REVIEWS
      - name: FACT_TALENT_CALIBRATIONS
      - name: DIM_JOB_DESC
      - name: FACT_POSITION_EVENTS
      - name: DIM_EVENT_CLASSIFICATION
      - name: DIM_UNION
      - name: DIM_ROLE_ASSIGNMENTS_BY_ORG
      - name: DIM_COMP_PLAN
      - name: DIM_BUSINESS_PROCESS
      - name: DIM_PAY_ACCUMULATORS
      - name: DIM_PAY_COMPONENT_GROUPS
      - name: DIM_PAYCODES
      - name: DIM_MANAGER_ORG
      - name: DIM_ORGANIZATION
      - name: DIM_COMP_GRADE_PROFILE
      - name: DIM_SUPERVISOR_ORG
      - name: FACT_COMPENSATION_CHANGES
      - name: DIM_LOCATION
      - name: DIM_PAY_COMPONENTS_REL_CALCS
      - name: DIM_PAY_ACCUMULATORS_ADD_TO
      - name: DIM_PAY_ACCUMULATORS_EXCEPTION_OPTION
      - name: DIM_PAy_ACCUMULATORS_SUBTRACT_FROM
      - name: DIM_COSTING_ALLOCATIONS
      - name: FACT_REFERRALS
      - name: DIM_EMPLOYEE_EVENTS

  - name: INBOUND_DENODO
    tables:
      - name: C_DIM_COA03489555691799999991932234255599531201275509125524477
      - name: C_FACT_CUSTOMER_SURVEY3092338126443464594840047527059059897454
      - name: C_FACT_GL_AMOUNT4691153832048177163719160045997332055528002872
      - name: C_FACT_GL_BUDGET8895164475594588974448916621422745083605849311
      - name: C_GL_ACCT_CATEGORY41822191382448977727429939268676679283319120
      - name: C_GL_ACCT_HIER617530945238820806236758211112758594208610222347
      - name: C_GL_LOB_CATEGORY764676357917747867360594763475623739855457042
      - name: C_GL_LOB_HIER9465712740231473509270154658194558665577075706448
      - name: C_RPT_CLAIM_FREQUENCY41354518787883831765779268157005836280957


 
  - name: EDW_CORE
    database: EDW
    schema: CORE
    tables:
      - name: DIM_CORP_HIER
