{{
    config(
        materialized='view'
    )
}}

select REGION_CD
, REGION_DESC
, AREA_CD
, AREA_DESC
, BUSINESS_UNIT_CD
, BUSINESS_UNIT_DESC
, CAST(CAST(DIVISION_CD as int) as VARCHAR) as DIVISION_CD
, DIVISION_DESC
, min(RPT_EFF_DT) as RPT_EFF_DT
, max(DISC_DT) as DISC_DT
from {{ ref('DIM_ORGANIZATION') }}
where is_current = 1
GROUP BY 
REGION_CD
, REGION_DESC
, AREA_CD
, AREA_DESC
, BUSINESS_UNIT_CD
, BUSINESS_UNIT_DESC
, DIVISION_CD
, DIVISION_DESC
QUALIFY ROW_NUMBER() OVER (PARTITION BY 
	REGION_CD
	, AREA_CD
	, BUSINESS_UNIT_CD
	, DIVISION_CD ORDER BY DIVISION_CD) = 1
