{{
    config(
        materialized='view'
    )
}}

select REGION_CD
, REGION_DESC
, AREA_CD,AREA_DESC
, BUSINESS_UNIT_CD
, BUSINESS_UNIT_DESC
, CAST(CAST(DIVISION_CD as int) as VARCHAR) as DIVISION_CD, DIVISION_DESC
, CAST(CAST(DEPARTMENT_CD as int) as VARCHAR) as DEPARTMENT_CD, DEPARTMENT_DESC
, LOCAL_USE_CD
, LOCAL_USE_DESC
, LEGAL_ENTITY_CD
, LEGAL_ENTITY_DESC
, COST_CENTER_CD
, COST_CENTER_DESC
, COST_CENTER_ID
, min(RPT_EFF_DT) as RPT_EFF_DT, max(disc_dt) as DISC_DT
from {{ ref('DIM_ORGANIZATION') }}
where is_current = 1
GROUP BY REGION_CD
, REGION_DESC
, AREA_CD
, AREA_DESC
, BUSINESS_UNIT_CD
, BUSINESS_UNIT_DESC
, DIVISION_CD
, DIVISION_DESC
, DEPARTMENT_CD
, DEPARTMENT_DESC
, LOCAL_USE_CD
, LOCAL_USE_DESC
, LEGAL_ENTITY_CD
, LEGAL_ENTITY_DESC
, COST_CENTER_CD
, COST_CENTER_DESC
, COST_CENTER_ID
QUALIFY ROW_NUMBER() OVER (PARTITION BY
	REGION_CD
	, AREA_CD
	, BUSINESS_UNIT_CD
	, DIVISION_CD
	, DEPARTMENT_CD
	, LEGAL_ENTITY_CD
	, LOCAL_USE_CD
	, COST_CENTER_CD
	ORDER BY DIVISION_CD, DEPARTMENT_CD, LOCAL_USE_CD) = 1
