{{
    config(
        materialized='incremental',
        unique_key ='AGENCY_USER_SK'
    )
}}

WITH
STG_AGENCY AS ( select * , 'WKD' AS REC_SOURCE
    from {{ source('STAGING','STG_WKD_RECRUITING_AGENCY') }} 
    
    {% if is_incremental() %}
     WHERE 
    RPT_EFFECTIVE_DT > ( select max(RPT_EFF_DT) from {{this}}  )
    {% endif %}
),
INS_BATCH_ID AS (
    SELECT TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) AS INS_BATCH_ID, 1 AS BATCH_KEY_ID
),

USER_AGENCY AS(
    SELECT 1 AS BATCH_KEY_ID,
    RECRUITING_AGENCY_REFID AS AGENCY_REF_ID,
    AGENCY_USER_REFID AS AGENCY_USER_ID,
    AGENCY_USER_EMAIL AS AGENCY_USER_EMAIL,
    AGENCY_USER_NAME AS AGENCY_USER_NAME,
    AGENCY_USER_UPDATED_DTM AS AGENCY_USER_UPD_DTM,
    AGENCY_USER_WID AS AGENCY_USER_WID,
    AGENCY_USER_WORK_PHONE AS AGENCY_USER_WORK_PHONE,
    RPT_EFFECTIVE_DT AS RPT_EFF_DT,
    REC_SOURCE AS REC_SRC,
    ROW_NUMBER() OVER(PARTITION BY RECRUITING_AGENCY_REFID, AGENCY_USER_REFID ORDER BY RPT_EFFECTIVE_DT DESC) RN, 
    TO_NUMBER(to_varchar(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) AS UPD_BATCH_ID
FROM STG_AGENCY
)

SELECT
    {{ dbt_utils.surrogate_key(['AGENCY_USER_ID']) }} AS AGENCY_USER_SK,
    AGENCY_REF_ID,
    AGENCY_USER_ID,
    AGENCY_USER_EMAIL,
    AGENCY_USER_NAME,
    AGENCY_USER_UPD_DTM,
    AGENCY_USER_WID,
    AGENCY_USER_WORK_PHONE,
    REC_SRC,
    RPT_EFF_DT,
    INS_BATCH_ID as INS_BATCH_ID,
    UPD_BATCH_ID
FROM USER_AGENCY
LEFT JOIN INS_BATCH_ID USING (BATCH_KEY_ID)
WHERE RN=1