{{
    config(
        materialized='table',
        unique_key ='EVENT_CLASS_SK',
        full_refresh = true
        )
}}

WITH
STG_EVENT AS (
    SELECT *, 'WKD' AS REC_SOURCE
    FROM {{ source('STAGING','STG_WKD_EVENT_CLASSIFICATION') }}
)

SELECT
{{ dbt_utils.surrogate_key(['EVENT_CLASS_SUBCAT_WID']) }} AS EVENT_CLASS_SK,
EVENT_CLASS_CAT_REFID AS CATEGORY_ID,
EVENT_CLASS_SUBCAT_REFID AS SUB_CATEGORY_ID,
EVENT_CLASS_CAT_WID AS CATEGORY_WID,
EVENT_CLASS_SUBCAT_WID AS SUB_CATEGORY_WID,
EVENT_CLASSIFICATION AS EVENT_CLASS,
EVENT_CLASS_CAT_INSTANCE AS CATEGORY_INSTANCE,
EVENT_CLASS_CATEGORY AS CATEGORY,
EVENT_CLASS_CAT_REASON AS CATEGORY_REASON,
EVENT_CLASS_SUBCAT_REASON AS SUB_CATEGORY_REASON,
MANAGER_REASON_IND AS MGR_REASON_IND,
TERM_REASON_INVOLUNTARY_IND AS TERM_REASON_INVOL_IND,
TERM_RETIREMENT_IND AS TERM_RETIREMENT_IND,
EVENT_CLASS_CAT_CREATED_DTM AS CATEGORY_CREATED_DTM,
EVENT_CLASS_SUBCAT_CREATED_DTM AS SUB_CATEGORY_CREATED_DTM,
TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) as INS_BATCH_ID,
TO_NUMBER(to_varchar(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) AS UPD_BATCH_ID,
REC_SOURCE AS REC_SRC
FROM STG_EVENT
QUALIFY ROW_NUMBER() OVER(PARTITION BY EVENT_CLASS_SUBCAT_WID ORDER BY SF_INSERT_TIMESTAMP DESC) = 1
