{{
    config(
        materialized='incremental',
        unique_key ='PCRC_SK'
        )
}}

WITH
STG_PAY_CALC AS (
    SELECT * , 'WKD' AS REC_SRC
    FROM {{ source('STAGING','STG_WKD_PAY_COMPONENT_RELATED_CALCULATIONS') }}

    {% if is_incremental() %}
     WHERE 
     RPT_EFFECTIVE_DT > ( select max(RPT_EFF_DT) from {{this}}  )
    {% endif %}
    
),

PAY_CALC AS (
    SELECT
    PCRC_WID AS PCRC_WID,
    PCRC_REFID AS PCRC_ID,
    PAYROLL_CALCULATION AS PAYROLL_CALC,
    COMPONENT_INTERFACE AS COMPONENT_INTERFACE,
    CALCULATION_TYPE AS CALC_TYPE,
    RELATED_CALCULATIONS AS RELATED_CALCS,
    PAYSLIP_NAME AS PAYSLIP_NAME,
    OVERRIDE_CALCULATION AS OVERRIDE_CALC,
    PCRC_COMMENT AS PCRC_COMMENT,
    PCRC_ORDER AS PCRC_ORDER,
    PAYROLL_COUNTRIES AS PAYROLL_COUNTRIES,
    TAXABLE_WAGES AS TAXABLE_WAGES,
    DISPLAY_OPTION AS DISPLAY_OPTION,
    CREATED_DTM AS CREATED_DTM,
    EFFECTIVE_DT AS EFF_DT,
    CALCULATION_CODE AS CALC_CD,
    CALCULATION_WORKTAG AS CALC_WORKTAG,
    CONDITIONAL_LIMIT_FILTER_WORKTAGS AS CONDITIONAL_LIMIT_FILTER_WORKTAGS,
    CONDITION_FOR_LIMIT_FILTER_WORKTAGS AS CONDITION_FOR_LIMIT_FILTER_WORKTAGS,
    DEFAULT_VALUE AS DEFAULT_VALUE,
    FLSA_PREMIUM_CALCULATION_TYPE AS FLSA_PREMIUM_CALC_TYPE,
    GROUPS AS GROUPS,
    HOURS_ON_RESULT_IND AS HRS_ON_RESULT_IND,
    INACTIVE_IND AS INACTIVE_IND,
    INCLUDE_RELATED_VALUES_CALCULATION AS INCLUDE_RELATED_VALUES_CALC,
    INCLUDE_VALUES_FROM_PREDECESSOR_IND AS INCLUDE_VALUES_FROM_PREDECESSOR_IND,
    LIMIT_BALANCE_PERIOD AS LIMIT_BALANCE_PERIOD,
    LIMIT_BASED_ON AS LIMIT_BASED_ON,
    LIMIT_VALUE AS LIMIT_VALUE,
    PAY_COMPONENT_GROUPS AS PAY_COMPONENT_GROUPS,
    PRORATION_METHOD AS PRORATION_METHOD,
    AGGREGATE_IND AS AGGREGATE_IND,
    ALLOW_INPUT_IND AS ALLOW_INPUT_IND,
    BRING_FORWARD_DIFFERENCE_IND AS BRING_FORWARD_DIFFERENCE_IND,
    CALCULATION_IN_USE_IND AS CALC_IN_USE_IND,
    DISPLAY_ON_RESULT_IND AS DISPLAY_ON_RESULT_IND,
    DONT_STORE_AS_RELATED_RESULT_LINE AS DONT_STORE_AS_RELATED_RESULT_LINE,
    DONT_STORE_AS_RELATED_RESULT_LINE_IF_ZERO AS DONT_STORE_AS_RELATED_RESULT_LINE_IF_ZERO,
    PRIVATE_IND AS PRIVATE_IND,
    PCRC_DONT_APPLY_PCT_SPLITS_MULT_WORK_JURISDICTIONS AS PCRC_DONT_APPLY_PCT_SPLITS_MULT_WORK_JURISDICTIONS,
    PCRC_APPLY_PCT_SPLITS_MULT_WORK_JURISDICTIONS AS PCRC_APPLY_PCT_SPLITS_MULT_WORK_JURISDICTIONS,
    COMMENT AS COMMENT,
    RPT_EFFECTIVE_DT AS RPT_EFF_DT,
    REC_SRC AS REC_SRC,
    TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) as INS_BATCH_ID,
    TO_NUMBER(to_varchar(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) AS UPD_BATCH_ID
    FROM STG_PAY_CALC
    QUALIFY ROW_NUMBER() OVER(PARTITION BY PCRC_WID ORDER BY RPT_EFFECTIVE_DT DESC) =1
)

SELECT
    {{ dbt_utils.surrogate_key(['PCRC_WID']) }} AS PCRC_SK,
    PCRC_WID,
    PCRC_ID,
    PAYROLL_CALC,
    COMPONENT_INTERFACE,
    CALC_TYPE,
    RELATED_CALCS,
    PAYSLIP_NAME,
    OVERRIDE_CALC,
    PCRC_COMMENT,
    PCRC_ORDER,
    PAYROLL_COUNTRIES,
    TAXABLE_WAGES,
    DISPLAY_OPTION,
    CREATED_DTM,
    EFF_DT,
    CALC_CD,
    CALC_WORKTAG,
    CONDITIONAL_LIMIT_FILTER_WORKTAGS,
    CONDITION_FOR_LIMIT_FILTER_WORKTAGS,
    DEFAULT_VALUE,
    FLSA_PREMIUM_CALC_TYPE,
    GROUPS,
    HRS_ON_RESULT_IND,
    INACTIVE_IND,
    INCLUDE_RELATED_VALUES_CALC,
    INCLUDE_VALUES_FROM_PREDECESSOR_IND,
    LIMIT_BALANCE_PERIOD,
    LIMIT_BASED_ON,
    LIMIT_VALUE,
    PAY_COMPONENT_GROUPS,
    PRORATION_METHOD,
    AGGREGATE_IND,
    ALLOW_INPUT_IND,
    BRING_FORWARD_DIFFERENCE_IND,
    CALC_IN_USE_IND,
    DISPLAY_ON_RESULT_IND,
    DONT_STORE_AS_RELATED_RESULT_LINE,
    DONT_STORE_AS_RELATED_RESULT_LINE_IF_ZERO,
    PRIVATE_IND,
    PCRC_DONT_APPLY_PCT_SPLITS_MULT_WORK_JURISDICTIONS,
    PCRC_APPLY_PCT_SPLITS_MULT_WORK_JURISDICTIONS,
    COMMENT,
    RPT_EFF_DT,
    REC_SRC,
    INS_BATCH_ID,
    UPD_BATCH_ID
FROM PAY_CALC
