{{
    config(
        materialized='table',
        unique_key ='JOB_SK',
        full_refresh = true
        )
}}

WITH
STG_WKD_JOB_CODE AS (
    SELECT *, 'WKD' AS REC_SOURCE
    FROM {{ source('STAGING','STG_WKD_JOB_CODE') }}
)

SELECT
{{ dbt_utils.surrogate_key(['JOB_CODE']) }} AS JOB_SK,
JOB_CODE AS JOB_CD,
JOB_WORKER_COMP_CODE AS JOB_WORKER_COMP_CD,
JOB_PROFILE_WID AS JOB_PROFILE_WID,
COMPENSATION_GRADE_WID AS COMP_GRADE_WID,
JOB_PROFILE_NAME AS JOB_PROFILE_NAME,
DEFAULT_JOB_TITLE AS DEFAULT_JOB_TITLE,
JOB_DESCRIPTION AS JOB_DESC,
JOB_PROFILE_INACTIVE_IND AS JOB_PROFILE_INACTIVE_IND,
JOB_PROFILE_LAST_UPD_DTM AS JOB_PROFILE_LAST_UPD_DTM,
ANNUAL_2080_HRS AS ANNUAL_2080_HRS,
JOB_MANAGEMENT_LEVEL AS JOB_MGMT_LEVEL,
JOB_FAMILY_GROUP AS JOB_FAMILY_GROUP,
JOB_FAMILY AS JOB_FAMILY,
PUBLIC_JOB_IND AS PUBLIC_JOB_IND,
DIFFICULTY_TO_FILL AS DIFFICULITY_TO_FILL,
CRITICAL_JOB_IND AS CRITICAL_JOB_IND,
JOB_PROFILE_EXEMPT_IND AS JOB_PROFILE_EXEMPT_IND,
WORK_SHIFT_REQUIRED_IND AS WORK_SHIFT_REQUIRED_IND,
JOB_PROFILE_PAY_RATE_TYPE AS JOB_PROFILE_PAY_RATE_TYPE,
NON_COMPETE AS NON_COMPETE,
RELOCATION_PACKAGE AS RELOCATION_PKG,
REFERRAL_PAYMENT_PLAN AS REFERRAL_PYMT_PLAN,
COMPANY_INSIDER_TYPE AS COMPANY_INSIDER_TYPE,
COMPENSATION_GRADE AS COMP_GRADE,
COMPENSATION_ELIGIBILITY_RULES AS COMP_ELIGIBILITY_RULES,
TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) as INS_BATCH_ID,
TO_NUMBER(to_varchar(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) AS UPD_BATCH_ID,
REC_SOURCE AS REC_SRC
FROM STG_WKD_JOB_CODE
QUALIFY ROW_NUMBER() OVER(PARTITION BY JOB_CODE ORDER BY SF_INSERT_TIMESTAMP::DATE DESC) = 1
