{{
    config(
        materialized='table',
        unique_key ='PAY_COMPONENT_GROUP_SK',
        full_refresh = True
        )
}}

WITH
STG_PAY_COMP_GROUP AS (
    SELECT *, 'WKD' AS REC_SOURCE
    FROM {{ source('STAGING','STG_WKD_PAY_COMPONENT_GROUPS') }}
)

SELECT
{{ dbt_utils.surrogate_key(['PAY_COMP_GRP_WID']) }} AS PAY_COMPONENT_GROUP_SK,
PAY_COMP_GRP_ID AS PAY_COMPONENT_GROUP_ID,
PAY_COMP_GRP_WID AS PAY_COMPONENT_GROUP_WID,
PAY_COMP_GRP_NAME AS PAY_COMPONENT_GROUP_NAME,
PAY_COMP_USAGE AS PAY_COMPONENT_USAGE,
CATEGORY AS CATEGORY,
CALCULATION_TYPE AS CALC_TYPE,
CALCULATION_IN_USE AS CALC_IN_USE,
PAY_COMP_RELATED_CALCS AS PAY_COMPONENT_RELATED_CALCS,
TAXABLE_WAGES AS TAXABLE_WAGES,
COUNTRIES AS COUNTRIES,
COMMENT AS COMMENT,
TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) as INS_BATCH_ID,
TO_NUMBER(to_varchar(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) AS UPD_BATCH_ID,
REC_SOURCE AS REC_SRC
FROM STG_PAY_COMP_GROUP
QUALIFY ROW_NUMBER() OVER(PARTITION BY PAY_COMPONENT_GROUP_WID ORDER BY SF_INSERT_TIMESTAMP DESC) = 1
