{{
    config(
        materialized='incremental',
        unique_key ='COMP_PLAN_SK'
    )
}}

WITH RAWDATA AS (
    SELECT *
    FROM {{ source('STAGING','STG_WKD_COMPENSATION_PLAN') }} 
        {% if is_incremental() %}
        WHERE  
        RPT_EFFECTIVE_DT > ( SELECT MAX(RPT_EFF_DT) FROM {{this}}  )
        {% endif %}
),

REQDATA AS (
    SELECT * 
    FROM {{ source('STAGING','STG_WKD_COMPENSATION_PLAN') }} 
    WHERE (
        ifnull(plan_wid, '') || '-' 
        || ifnull(comp_element_wid, '') || '-' 
        || ifnull(eligibility_rules_wid, '') || '-' 
        || ifnull(ifnull(plan_profile_wid, plan_profile_target_rules_sens), '') ) IN 
        (SELECT     (ifnull(plan_wid, '') || '-' 
        || ifnull(comp_element_wid, '') || '-' 
        || ifnull(eligibility_rules_wid, '') || '-' 
        || ifnull(ifnull(plan_profile_wid, plan_profile_target_rules_sens), '') )
            FROM {{ source('STAGING','STG_WKD_COMPENSATION_PLAN') }} 
         )

),

COMP AS(
    SELECT 
    Plan_REFID_SENS AS PLAN_ID_SENS,
    Plan_WID AS PLAN_WID,
    Comp_Element_WID AS COMP_ELEMENT_WID,
    Comp_Element_REFID_SENS AS COMP_ELEMENT_ID_SENS,
    Plan_Eligibility_Rule_REFID_SENS AS PLAN_ELIGIBILITY_RULE_ID_SENS,
    Eligibility_Rules_WID AS ELIGIBILITY_RULES_WID,
    Plan_Profile_WID AS PLAN_PROFILE_WID,
    Plan_Name AS PLAN_NAME, 
    Plan_Type_SENS AS PLAN_TYPE_SENS,
    Plan_Comp_Packages AS PLAN_COMP_PKGS,
    Compensation_Components_SENS AS COMP_COMPONENTS_SENS,
    Plan_Comp_Basis_SENS AS PLAN_COMP_BASIS_SENS,
    Plan_AMT_SENS AS PLAN_AMT_SENS,
    Plan_Apply_FTE_Percent_SENS AS PLAN_APPLY_FTE_PCT_SENS,
    Plan_Frequency_SENS AS PLAN_FREQ_SENS,
    Plan_Inactive AS PLAN_INACTIVE,
    Plan_Created_DTM AS PLAN_CREATED_DTM,
    Comp_Plan_Last_Functionally_Updated AS PLAN_LAST_FUNCTIONALLY_UPD,
    Plan_Comp_Element_SENS AS COMP_ELEMENT_SENS,
    Comp_Element_Grade_Profile_SENS AS COMP_ELEMENT_GRADE_PROFILE_SENS,
    Comp_Element_Groups_SENS AS COMP_ELEMENT_GROUPS_SENS,
    Comp_Element_Created_DTM AS COMP_ELEMENT_CREATED_DTM,
    Plan_Eligibility_Rule_SENS AS ELIGIBILITY_RULE_SENS,
    Eligibility_Rule_Last_Functionally_Updated AS ELIGIBILITY_RULE_LAST_FUNCTIONALLY_UPD,
    Condition_Rule_as_Text_SENS AS CONDITION_RULE_AS_TEXT_SENS,
    Current_Usages_SENS AS CURR_USAGES_SENS,
    Created_From_SENS AS CREATED_FROM_SENS,
    Used_As_SENS AS USED_AS_SENS,
    Used_as_a_Sub_Rule_From_Item_SENS AS USED_AS_A_SUB_RULE_FROM_ITEM_SENS,
    Plan_Profiles_SENS AS PLAN_PROFILES_SENS,
    Plan_Profile_Target_AMT_SENS AS PLAN_PROFILE_TARGET_AMT_SENS,
    Plan_Profile_Target_Percent_SENS AS PLAN_PROFILE_TARGET_PCT_SENS,
    Plan_Profile_Target_Rules_SENS AS PLAN_PROFILE_TARGET_RULES_SENS,
    RPT_Effective_DT AS RPT_EFF_DT,
    ROW_NUMBER() OVER (PARTITION BY PLAN_REFID_SENS,
    PLAN_WID,
    COMP_ELEMENT_WID,
    COMP_ELEMENT_REFID_SENS,
    PLAN_ELIGIBILITY_RULE_REFID_SENS,
    ELIGIBILITY_RULES_WID,
    PLAN_PROFILE_WID,
    PLAN_NAME,
    PLAN_TYPE_SENS,
    PLAN_COMP_PACKAGES,
    COMPENSATION_COMPONENTS_SENS,
    PLAN_COMP_BASIS_SENS,
    PLAN_AMT_SENS,
    PLAN_APPLY_FTE_PERCENT_SENS,
    PLAN_FREQUENCY_SENS,
    PLAN_INACTIVE,
    PLAN_CREATED_DTM,
    COMP_PLAN_LAST_FUNCTIONALLY_UPDATED,
    PLAN_COMP_ELEMENT_SENS,
    COMP_ELEMENT_GRADE_PROFILE_SENS,
    COMP_ELEMENT_GROUPS_SENS,
    COMP_ELEMENT_CREATED_DTM,
    PLAN_ELIGIBILITY_RULE_SENS,
    ELIGIBILITY_RULE_LAST_FUNCTIONALLY_UPDATED,
    CONDITION_RULE_AS_TEXT_SENS,
    CURRENT_USAGES_SENS,
    CREATED_FROM_SENS,
    USED_AS_SENS,
    USED_AS_A_SUB_RULE_FROM_ITEM_SENS,
    PLAN_PROFILES_SENS,
    PLAN_PROFILE_TARGET_AMT_SENS,
    PLAN_PROFILE_TARGET_PERCENT_SENS,
    PLAN_PROFILE_TARGET_RULES_SENS  ORDER BY RPT_EFFECTIVE_DT) AS RN
FROM REQDATA
QUALIFY RN =1 ),

VERSION AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY COALESCE(PLAN_WID,''),COALESCE(COMP_ELEMENT_WID,''),COALESCE(ELIGIBILITY_RULES_WID,''),
    COALESCE(COALESCE(PLAN_PROFILE_WID,PLAN_PROFILE_TARGET_RULES_SENS),'')
    ORDER BY RPT_EFF_DT DESC) 
    AS VERSION_NUMBER FROM COMP
),


FINAL AS (
    SELECT V1.*, V1.RPT_EFF_DT AS EFF_DT, V2.RPT_EFF_DT -1  AS DISC_DT
    FROM VERSION V1 
    LEFT JOIN VERSION V2 ON V1.VERSION_NUMBER -1 =V2.VERSION_NUMBER 
    AND (V1.PLAN_WID = V2.PLAN_WID OR V1.PLAN_WID IS NULL OR V2.PLAN_WID IS NULL)
    AND (V1.COMP_ELEMENT_WID = V2.COMP_ELEMENT_WID OR V1.COMP_ELEMENT_WID IS NULL OR V2.COMP_ELEMENT_WID IS NULL)
    AND (V1.ELIGIBILITY_RULES_WID = V2.ELIGIBILITY_RULES_WID OR V1.ELIGIBILITY_RULES_WID IS NULL OR V2.ELIGIBILITY_RULES_WID IS NULL)
    AND (V1.PLAN_PROFILE_WID = V2.PLAN_PROFILE_WID OR V1.PLAN_PROFILE_WID IS NULL OR V2.PLAN_PROFILE_WID IS NULL)
    AND (V1.PLAN_PROFILE_TARGET_RULES_SENS = V2.PLAN_PROFILE_TARGET_RULES_SENS   
    OR V1.PLAN_PROFILE_TARGET_RULES_SENS IS NULL OR V2.PLAN_PROFILE_TARGET_RULES_SENS IS NULL)

    ORDER BY V1.VERSION_NUMBER
)

SELECT 
    {{ dbt_utils.surrogate_key(['PLAN_WID','COMP_ELEMENT_WID','ELIGIBILITY_RULES_WID','PLAN_PROFILE_WID','PLAN_PROFILE_TARGET_RULES_SENS','RPT_EFF_DT']) }} AS COMP_PLAN_SK,
    ifnull(plan_wid, '') || '-' 
        || ifnull(comp_element_wid, '') || '-' 
        || ifnull(eligibility_rules_wid, '') || '-' 
        || ifnull(ifnull(plan_profile_wid, plan_profile_target_rules_sens), '') AS COMP_PLAN_ID,
    PLAN_ID_SENS,
    PLAN_WID,
    COMP_ELEMENT_WID,
    COMP_ELEMENT_ID_SENS,
    PLAN_ELIGIBILITY_RULE_ID_SENS,
    ELIGIBILITY_RULES_WID,
    PLAN_PROFILE_WID,
    PLAN_NAME,
    PLAN_TYPE_SENS,
    PLAN_COMP_PKGS,
    COMP_COMPONENTS_SENS,
    PLAN_COMP_BASIS_SENS,
    PLAN_AMT_SENS,
    PLAN_APPLY_FTE_PCT_SENS,
    PLAN_FREQ_SENS,
    PLAN_INACTIVE,
    PLAN_CREATED_DTM,
    PLAN_LAST_FUNCTIONALLY_UPD,
    COMP_ELEMENT_SENS,
    COMP_ELEMENT_GRADE_PROFILE_SENS,
    COMP_ELEMENT_GROUPS_SENS,
    COMP_ELEMENT_CREATED_DTM,
    ELIGIBILITY_RULE_SENS,
    ELIGIBILITY_RULE_LAST_FUNCTIONALLY_UPD,
    CONDITION_RULE_AS_TEXT_SENS,
    CURR_USAGES_SENS,
    CREATED_FROM_SENS,
    USED_AS_SENS,
    USED_AS_A_SUB_RULE_FROM_ITEM_SENS,
    PLAN_PROFILES_SENS,
    PLAN_PROFILE_TARGET_AMT_SENS,
    PLAN_PROFILE_TARGET_PCT_SENS,
    PLAN_PROFILE_TARGET_RULES_SENS,
    RPT_EFF_DT,
    'WKD' AS REC_SRC,
    EFF_DT, 
    COALESCE(DISC_DT, '9999-12-31') as DISC_DT,
    CASE WHEN DISC_DT IS NULL THEN TRUE ELSE FALSE END AS IS_CURRENT,         
    (SELECT TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS'))) AS INS_BATCH_ID,
    TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) AS UPD_BATCH_ID,
    {{ dbt_utils.surrogate_key(['PLAN_ID_SENS','COMP_ELEMENT_ID_SENS','PLAN_ELIGIBILITY_RULE_ID_SENS','PLAN_NAME','PLAN_TYPE_SENS','PLAN_COMP_PKGS','COMP_COMPONENTS_SENS','PLAN_COMP_BASIS_SENS','PLAN_AMT_SENS','PLAN_APPLY_FTE_PCT_SENS','PLAN_FREQ_SENS','PLAN_INACTIVE',
    'PLAN_CREATED_DTM','PLAN_LAST_FUNCTIONALLY_UPD','COMP_ELEMENT_SENS','COMP_ELEMENT_GRADE_PROFILE_SENS','COMP_ELEMENT_GROUPS_SENS','COMP_ELEMENT_CREATED_DTM','ELIGIBILITY_RULE_SENS','ELIGIBILITY_RULE_LAST_FUNCTIONALLY_UPD','CONDITION_RULE_AS_TEXT_SENS','CURR_USAGES_SENS','CREATED_FROM_SENS','USED_AS_SENS','USED_AS_A_SUB_RULE_FROM_ITEM_SENS','PLAN_PROFILES_SENS','PLAN_PROFILE_TARGET_AMT_SENS','PLAN_PROFILE_TARGET_PCT_SENS']) }} AS DBT_HASH
FROM FINAL