{{
    config(
        materialized='incremental',
        unique_key ='JOB_REQ_SK',
        full_refresh = false
        )
}}
-- Took out post_hook="ALTER SESSION SET TIMESTAMP_OUTPUT_FORMAT = 'YYYY-MM-DD HH24:MI:SS';",

WITH
STG_WKD_JOB_REQUISITION AS ( 
    select stg.* 
    , 'WKD' AS REC_SOURCE
    , stg.BP_COMPLETED_DTM AS PAR_COLUMN
    {% if is_incremental() %}
    , dim.job_req_sk
    {% endif %}
    from {{ source('STAGING','STG_WKD_JOB_REQUISITION') }} stg
    {% if is_incremental() %}
    left join {{this}} dim on dim.job_req_id = stg.job_req_id
    {% endif %}
    WHERE 1=1
    {% if is_incremental() %}
    and stg.BP_COMPLETED_DTM > nvl(dim.BP_COMPLETED_DTM, '1900-01-01')
    {% endif %}
    QUALIFY ROW_NUMBER() OVER(PARTITION BY STG.JOB_REQ_ID  ORDER BY PAR_COLUMN desc) = 1
),

JOB_REQUISITION AS (
    SELECT 1 AS BATCH_KEY_ID,
    JOB_REQ_ID AS JOB_REQ_ID,
    POSITION_ID AS POSITION_ID,
    JOB_CODE AS JOB_CD,
    COMPANY_ID AS COMPANY_ID,
    COST_CENTER_ID AS COST_CENTER_ID,
    REPLACEMENT_FOR_EIN AS REPLACEMENT_FOR_EMP_ID,
    INITIATOR_EIN AS INITIATOR_EMP_ID,
    APPROVED_BY_EIN AS APPROVED_BY_EMP_ID,
    RECRUITER_EIN AS RECRUITER_EMP_ID,
    HIRING_MANAGER_EIN AS HIRING_MGR_EMP_ID,
    SUPERVISORY_ORG_ID AS SUPERVISORY_ORG_ID,
    SUP_ORG_AS_OF_DATE_FILLED AS SUP_ORG_AS_OF_DATE_FILLED,
    PRIMARY_LOCATION_ID AS PRIM_LOCATION_ID,
    PRIMARY_JOB_POSTING_LOCATION_ID AS PRIM_JOB_POSTING_LOCATION_ID,
    OTHER_JOB_POSTING_LOCATIONS AS OTHER_JOB_POSTING_LOCATIONS,
    JOB_APP_TEMPLATE_ID AS JOB_APP_TEMPLATE_ID,
    PRIMARY_EXTERNAL_QUESTIONNAIRE_ID AS PRIM_EXT_QSTR_ID,
    SECONDARY_EXTERNAL_QUESTIONNAIRE_ID AS SECONDARY_EXT_QSTR_ID,
    PRIMARY_INTERNAL_QUESTIONNAIRE_ID AS PRIM_INT_QSTR_ID,
    SECONDARY_INTERNAL_QUESTIONNAIRE_ID AS SECONDARY_INT_QSTR_ID,
    JOB_REQ_EVENT_WID AS JOB_REQ_EVENT_WID,
    JOB_POSTING_TITLE AS JOB_POSTING_TITLE,
    JOB_DESCRIPTION AS JOB_DESC_AT_POSTING,
    EVERGREEN_IND AS EVERGREEN_IND,
    LINKED_EVERGREEN_REQ_ID AS LINKED_EVERGREEN_REQ_ID,
    JOB_REQ_STATUS AS JOB_REQ_STATUS,
    CREATED_REASON AS CREATED_REASON,
    QUALIFICATIONS AS QUALIFICATIONS,
    OVERALL_INTERVIEW_COMMENTS AS OVERALL_INTERVIEW_COMMENTS,
    BP_COMPLETED_DTM AS BP_COMPLETED_DTM,
    JOB_REQ_ENTERED_DT AS JOB_REQ_ENTERED_DT,
    JOB_REQ_FILLED_DT AS JOB_REQ_FILLED_DT,
    JOB_REQ_COMPLETED_DT AS JOB_REQ_COMPLETED_DT,
    TARGET_HIRE_DT AS TARGET_HIRE_DT,
    TARGET_END_DT AS TARGET_END_DT,
    RECRUITMENT_START_DT AS RECRUIT_START_DT,
    JOB_REQ_CLOSED_DT AS JOB_REQ_CLOSED_DT,
    HIRING_FREEZE_IND AS HIRING_FREEZE_IND,
    JOB_REQ_FREEZE_DT AS JOB_REQ_FREEZE_DT,
    JOB_REQ_UNFREEZE_DT AS JOB_REQ_UNFREEZE_DT,
    LATEST_OFFER_COMPLETED_DT AS LATEST_OFFER_COMPLETED_DT,
    LATEST_HIRE_DT AS LATEST_HIRE_DT,
    LATEST_HIRE_INITIATION_DT AS LATEST_HIRE_INITIATION_DT,
    AVAIL_FOR_HIRE_IND AS AVAIL_FOR_HIRE_IND,
    AVAIL_FOR_OVERLAP_IND AS AVAIL_FOR_OVERLAP_IND,
    SPOTLIGHT_JOB_IND AS SPOTLIGHT_JOB_IND,
    SCHEDULED_WEEKLY_HOURS AS SCHEDULED_WEEKLY_HRS,
    WORK_SHIFT AS WORK_SHIFT,
    COMPENSATION_GRADE_PROFILE AS COMP_GRADE_PROFILE,
    COMPENSATION_GRADE AS COMP_GRADE,
    COMPENSATION_AMOUNT AS COMP_AMT,
    WORKER_TYPE AS WORKER_TYPE,
    WORKER_SUB_TYPE AS WORKER_SUB_TYPE,
    TIME_TYPE AS TIME_TYPE,
    POSTED_EXTERNALLY_IND AS POSTED_EXT_IND,
    POSTED_INTERNALLY_IND AS POSTED_INT_IND,
    RECRUITING_AGENCY AS AGENCY,
    RECRUITING_AGENCY_USER_DETAILS AS AGENCY_USER_DTL,
    JOB_REQ_EVENT_LINK AS JOB_REQ_EVENT_LINK,
    JOB_REQ_OTHER_DATA AS JOB_REQ_OTHER_DATA,
    REC_SOURCE AS REC_SRC,
    TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) AS INS_BATCH_ID,
    TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) AS UPD_BATCH_ID
FROM STG_WKD_JOB_REQUISITION
)

SELECT
    {{ dbt_utils.surrogate_key(['JOB_REQ_ID']) }} as JOB_REQ_SK,
    JOB_REQ_ID,
    POSITION_ID,
    JOB_CD,
    COMPANY_ID,
    COST_CENTER_ID,
    REPLACEMENT_FOR_EMP_ID,
    INITIATOR_EMP_ID,
    APPROVED_BY_EMP_ID,
    RECRUITER_EMP_ID,
    HIRING_MGR_EMP_ID,
    SUPERVISORY_ORG_ID,
    SUP_ORG_AS_OF_DATE_FILLED,
    PRIM_LOCATION_ID,
    PRIM_JOB_POSTING_LOCATION_ID,
    OTHER_JOB_POSTING_LOCATIONS,
    JOB_APP_TEMPLATE_ID,
    PRIM_EXT_QSTR_ID,
    SECONDARY_EXT_QSTR_ID,
    PRIM_INT_QSTR_ID,
    SECONDARY_INT_QSTR_ID,
    JOB_REQ_EVENT_WID,
    JOB_POSTING_TITLE,
    JOB_DESC_AT_POSTING,
    EVERGREEN_IND,
    LINKED_EVERGREEN_REQ_ID,
    JOB_REQ_STATUS,
    CREATED_REASON,
    QUALIFICATIONS,
    OVERALL_INTERVIEW_COMMENTS,
    BP_COMPLETED_DTM,
    JOB_REQ_ENTERED_DT,
    JOB_REQ_FILLED_DT,
    JOB_REQ_COMPLETED_DT,
    TARGET_HIRE_DT,
    TARGET_END_DT,
    RECRUIT_START_DT,
    JOB_REQ_CLOSED_DT,
    HIRING_FREEZE_IND,
    JOB_REQ_FREEZE_DT,
    JOB_REQ_UNFREEZE_DT,
    LATEST_OFFER_COMPLETED_DT,
    LATEST_HIRE_DT,
    LATEST_HIRE_INITIATION_DT,
    AVAIL_FOR_HIRE_IND,
    AVAIL_FOR_OVERLAP_IND,
    SPOTLIGHT_JOB_IND,
    SCHEDULED_WEEKLY_HRS,
    WORK_SHIFT,
    COMP_GRADE_PROFILE,
    COMP_GRADE,
    COMP_AMT,
    WORKER_TYPE,
    WORKER_SUB_TYPE,
    TIME_TYPE,
    POSTED_EXT_IND,
    POSTED_INT_IND,
    AGENCY,
    AGENCY_USER_DTL,
    JOB_REQ_EVENT_LINK,
    JOB_REQ_OTHER_DATA,
    REC_SRC,
    INS_BATCH_ID,
    UPD_BATCH_ID
FROM JOB_REQUISITION
