{{
    config(
        materialized='table',
        unique_key ='PAY_ACCUMULATION_SK',
        full_refresh = True
        )
}}

WITH
STG_PAY_ACC AS (
    SELECT *, 'WKD' AS REC_SOURCE
    FROM {{ source('STAGING','STG_WKD_PAY_ACCUMULATORS') }}
)

SELECT
{{ dbt_utils.surrogate_key(['PAY_ACCUMULATION_WID']) }} AS PAY_ACCUMULATION_SK,
PAY_ACCUMULATION_WID AS PAY_ACCUMULATION_WID,
PAY_ACCUMULATION_CD AS PAY_ACCUMULATION_CD,
CALCULATION_TYPE AS CALC_TYPE,
CALCULATION_TYPE_ID AS CALC_TYPE_ID,
CALCULATION_WORKTAG AS CALC_WORKTAG,
CALCULATION_IN_USE_IND AS CALC_IN_USE_IND,
PRIVATE_IND AS PRIVATE_IND,
CATEGORY AS CATEGORY,
CALC_DISPLAY_EXCEPTION AS CALC_DISPLAY_EXCEPTION,
LIMIT_VALUE AS LIMIT_VALUE,
LIMIT_BALANCE_PERIOD AS LIMIT_BALANCE_PERIOD,
LIMIT_BASED_ON AS LIMIT_BASED_ON,
PAY_ACCUMULATION_DESC AS PAY_ACCUMULATION_DESC,
COMMENT AS COMMENT,
COUNTRIES AS COUNTRIES,
TAXABLE_WAGES AS TAXABLE_WAGES,
GTN_TYPE AS GTN_TYPE,
PAY_ACCUMULATION_CREATED_DTM AS CREATED_DTM,
PAY_ACCUMULATION_LAST_FUNCTIONALLY_UPD_DTM AS LAST_FUNCTIONALLY_UPD_DTM,
TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) as INS_BATCH_ID,
TO_NUMBER(to_varchar(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) AS UPD_BATCH_ID,
REC_SOURCE AS REC_SRC
FROM STG_PAY_ACC
QUALIFY ROW_NUMBER() OVER(PARTITION BY PAY_ACCUMULATION_WID ORDER BY SF_INSERT_TIMESTAMP DESC) = 1
