{{
    config(
        materialized='incremental',
        unique_key='TIME_OFF_SK',
        full_refresh=false
        )
}}

WITH
STG_WKD_WORKER_TIME_OFF AS (
    SELECT *, 'WKD' AS REC_SOURCE
    FROM {{ source('STAGING','STG_WKD_WORKER_TIME_OFF') }}
    {% if is_incremental() %}
     WHERE 
     (TO_NUMBER(to_varchar(TIME_OFF_ENTRY_DT, 'YYYYMMDDHH24MISSFF3'))  >= '{{ get_max_event_time('INS_BATCH_ID') }}'
      OR TO_NUMBER(to_varchar(TIME_OFF_ENTRY_APPROVED_DT, 'YYYYMMDDHH24MISSFF3'))  >= '{{ get_max_event_time('INS_BATCH_ID') }}'
      OR TO_NUMBER(to_varchar(TIME_OFF_DT, 'YYYYMMDDHH24MISSFF3'))  >= '{{ get_max_event_time('INS_BATCH_ID') }}'
     )
    {% endif %}
)

SELECT
{{ dbt_utils.surrogate_key(['TIME_OFF_ENTRY_WID']) }} AS TIME_OFF_SK,
EMPLOYEE_ID AS EMP_ID,
TIME_OFF_ENTRY_WID AS TIME_OFF_ENTRY_WID,
TIME_OFF_BP_ACTION_WID AS TIME_OFF_BP_ACTION_WID,
TIME_OFF_BP_ACTION AS TIME_OFF_BP_ACTION,
TIME_OFF_ENTRY_DESC AS ENTRY_DESC,
REQUEST_OR_CORRECTION AS REQUEST_OR_CORRECTION,
TIME_OFF_TYPE_SENS AS TYPE_SENS,
TIME_OFF_ENTRY_DT AS ENTRY_DT,
TIME_OFF_ENTRY_STATUS AS ENTRY_STATUS,
TIME_OFF_ENTRY_APPROVED_DTM AS ENTRY_APPROVED_DTM,
TIME_OFF_ENTRY_APPROVED_DT AS ENTRY_APPROVED_DT,
APPROVED_BY AS APPROVED_BY,
TIME_OFF_DT AS TIME_OFF_DT,
TIME_OFF_APPROVED_HRS AS APPROVED_HRS,
TIME_OFF_PENDING_HRS AS PENDING_HRS,
TIME_OFF_DENIED_HRS AS DENIED_HRS,
TIME_OFF_ENTRY_COMMENT_SENS AS ENTRY_COMMENT_SENS,
TIME_OFF_ENTRY_REASON_SENS AS ENTRY_REASON_SENS,
TIME_OFF_IN_BALANCE_PERIOD_HRS AS TIME_OFF_IN_BALANCE_PERIOD_HRS,
TIME_OFF_ACCRUED_AS_OF_ENTRY_HRS AS TIME_OFF_ACCRUED_AS_OF_ENTRY_HRS,
AVAILABLE_BALANCE_MORE_TIME_OFF_IND AS AVAILABLE_BALANCE_MORE_TIME_OFF_IND,
TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) as INS_BATCH_ID,
TO_NUMBER(to_varchar(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')) AS UPD_BATCH_ID,
REC_SOURCE AS REC_SRC
FROM STG_WKD_WORKER_TIME_OFF
QUALIFY ROW_NUMBER() OVER(PARTITION BY TIME_OFF_ENTRY_WID ORDER BY TIME_OFF_ENTRY_DT DESC
    , TIME_OFF_ENTRY_APPROVED_DT DESC, TIME_OFF_DT DESC) = 1
